serve:
  port: 5000
  browser: true
  playground: true
sources:
  - name: Countries
    handler:
      graphql:
        endpoint: https://countries.trevorblades.com
  - name: StackExchange
    handler:
      openapi:
        source: https://raw.githubusercontent.com/grokify/api-specs/master/stackexchange/stackexchange-api-v2.2_openapi-v3.0.yaml
  - name: OBS
    handler:
      graphql:
        endpoint: http://10.240.118.8:5005/graphql
        operationHeaders:
          Authorization: Bearer {context.headers['my-api-token']} 
additionalTypeDefs: [./src/types.graphql, ./src/extraTypes.graphql]
additionalResolvers:
  - ./src/additional-resolvers.js
  - ./src/people-resolver.js
documents:
  - example.graphql
